version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  huey:
    build: .
    container_name: huey_worker
    command: python manage.py run_huey
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data:
